server:
  port: 8090
spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/1234
    username: root
    password: root

  application:
    name: reactive_r2dbc_mysql_client
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
